# Bash completion for doorstop
# Generated by bin/generate-completions

_doorstop() {
    local cur prev words cword
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words="${COMP_WORDS[@]}"
    cword="${COMP_CWORD}"

    # Commands
    local commands="create delete add remove edit reorder link unlink clear review import export publish serve"
    
    # Global options
    local global_opts="-j --project --server --port -f --force -V --version -v --verbose -q --quiet -F --no-reformat -r --reorder -L --no-level-check -R --no-ref-check -C --no-child-check -Z --strict-child-check -S --no-suspect-check -W --no-review-check -s --skip -w --warn-all -e --error-all"
    
    # Complete commands
    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "${commands} ${global_opts}" -- "${cur}"))
        return 0
    fi
    
    # Complete options for commands
    case "${prev}" in
        -j|--project|--server|--port|-s|--skip)
            COMPREPLY=($(compgen -f -- "${cur}"))
            return 0
            ;;
    esac
    
    # Complete command-specific options
    local cmd="${COMP_WORDS[1]}"
    case "${cmd}" in
        create|add|edit|import|export|publish)
            COMPREPLY=($(compgen -W "${global_opts}" -- "${cur}"))
            ;;
        *)
            COMPREPLY=($(compgen -W "${global_opts}" -- "${cur}"))
            ;;
    esac
}

complete -F _doorstop doorstop
