# Fish completion for doorstop
# Generated by bin/generate-completions

complete -c doorstop -f

# Commands
complete -c doorstop -n '__fish_use_subcommand' -a create -d 'create a new document directory'
complete -c doorstop -n '__fish_use_subcommand' -a delete -d 'delete a document directory'
complete -c doorstop -n '__fish_use_subcommand' -a add -d 'create an item file in a document directory'
complete -c doorstop -n '__fish_use_subcommand' -a remove -d 'remove an item file from a document directory'
complete -c doorstop -n '__fish_use_subcommand' -a edit -d 'edit an item file'
complete -c doorstop -n '__fish_use_subcommand' -a reorder -d 'reorder document levels'
complete -c doorstop -n '__fish_use_subcommand' -a link -d 'link items together'
complete -c doorstop -n '__fish_use_subcommand' -a unlink -d 'unlink items'
complete -c doorstop -n '__fish_use_subcommand' -a clear -d 'clear item links'
complete -c doorstop -n '__fish_use_subcommand' -a review -d 'review items'
complete -c doorstop -n '__fish_use_subcommand' -a import -d 'import requirements from a file'
complete -c doorstop -n '__fish_use_subcommand' -a export -d 'export requirements to a file'
complete -c doorstop -n '__fish_use_subcommand' -a publish -d 'publish documents'
complete -c doorstop -n '__fish_use_subcommand' -a serve -d 'serve documents via web interface'

# Global options
complete -c doorstop -s j -l project -d 'path to the root of the project' -r
complete -c doorstop -l server -d 'IP address or hostname for a running server' -r
complete -c doorstop -l port -d 'use a custom port for the server' -r
complete -c doorstop -s f -l force -d 'perform the action without the server'
complete -c doorstop -s V -l version -d 'show version'
complete -c doorstop -s v -l verbose -d 'enable verbose logging'
complete -c doorstop -s q -l quiet -d 'only display errors and prompts'
complete -c doorstop -s F -l no-reformat -d 'do not reformat item files during validation'
complete -c doorstop -s r -l reorder -d 'reorder document levels during validation'
complete -c doorstop -s L -l no-level-check -d 'do not validate document levels'
complete -c doorstop -s R -l no-ref-check -d 'do not validate external file references'
complete -c doorstop -s C -l no-child-check -d 'do not validate child (reverse) links'
complete -c doorstop -s Z -l strict-child-check -d 'require child (reverse) links from every document'
complete -c doorstop -s S -l no-suspect-check -d 'do not check for suspect links'
complete -c doorstop -s W -l no-review-check -d 'do not check item review status'
complete -c doorstop -s s -l skip -d 'skip a document during validation' -r
complete -c doorstop -s w -l warn-all -d 'display all info-level issues as warnings'
complete -c doorstop -s e -l error-all -d 'display all warnings as errors'
